//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class ObjectsInfoWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(ObjectsInfo), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("GetObjectInfoById", GetObjectInfoById);
		L.RegFunction("ReadInfo", ReadInfo);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Instance", get_Instance, set_Instance);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetObjectInfoById(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ObjectsInfo obj = (ObjectsInfo)ToLua.CheckObject(L, 1, typeof(ObjectsInfo));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			ObjectInfo o = obj.GetObjectInfoById(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ReadInfo(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ObjectsInfo obj = (ObjectsInfo)ToLua.CheckObject(L, 1, typeof(ObjectsInfo));
			UnityEngine.TextAsset arg0 = (UnityEngine.TextAsset)ToLua.CheckUnityObject(L, 2, typeof(UnityEngine.TextAsset));
			obj.ReadInfo(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Instance(IntPtr L)
	{
		try
		{
			ToLua.Push(L, ObjectsInfo.Instance);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Instance(IntPtr L)
	{
		try
		{
			ObjectsInfo arg0 = (ObjectsInfo)ToLua.CheckUnityObject(L, 2, typeof(ObjectsInfo));
			ObjectsInfo.Instance = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

