//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;
using Object = UnityEngine.Object;

public class ShopWeaponItemWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(ShopWeaponItem), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("SetId", SetId);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetId(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			ShopWeaponItem obj = (ShopWeaponItem)ToLua.CheckObject(L, 1, typeof(ShopWeaponItem));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			UnityEngine.Object[] arg1 = ToLua.CheckObjectArray<UnityEngine.Object>(L, 3);
			UnityEngine.GameObject arg2 = (UnityEngine.GameObject)ToLua.CheckUnityObject(L, 4, typeof(UnityEngine.GameObject));
			obj.SetId(arg0, arg1, arg2);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

