//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class SigninSqWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(SigninSq), typeof(U3DEventFrame.UIBase));
		L.RegFunction("OnClickOk", OnClickOk);
		L.RegFunction("HandoverScene2", HandoverScene2);
		L.RegFunction("ProgressBarExecute", ProgressBarExecute);
		L.RegFunction("ProcessEvent", ProcessEvent);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnClickOk(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			SigninSq obj = (SigninSq)ToLua.CheckObject(L, 1, typeof(SigninSq));
			UnityEngine.UI.Text arg0 = (UnityEngine.UI.Text)ToLua.CheckUnityObject(L, 2, typeof(UnityEngine.UI.Text));
			string arg1 = ToLua.CheckString(L, 3);
			string arg2 = ToLua.CheckString(L, 4);
			obj.OnClickOk(arg0, arg1, arg2);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int HandoverScene2(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			SigninSq obj = (SigninSq)ToLua.CheckObject(L, 1, typeof(SigninSq));
			obj.HandoverScene2();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ProgressBarExecute(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			SigninSq obj = (SigninSq)ToLua.CheckObject(L, 1, typeof(SigninSq));
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckUnityObject(L, 2, typeof(UnityEngine.GameObject));
			obj.ProgressBarExecute(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ProcessEvent(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			SigninSq obj = (SigninSq)ToLua.CheckObject(L, 1, typeof(SigninSq));
			U3DEventFrame.MsgBase arg0 = (U3DEventFrame.MsgBase)ToLua.CheckObject(L, 2, typeof(U3DEventFrame.MsgBase));
			obj.ProcessEvent(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

