//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class U3DEventFrame_UIBaseWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(U3DEventFrame.UIBase), typeof(U3DEventFrame.MonoBase));
		L.RegFunction("RegistSelf", RegistSelf);
		L.RegFunction("UnRegistSelf", UnRegistSelf);
		L.RegFunction("SendMsg", SendMsg);
		L.RegFunction("OnDestroy", OnDestroy);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("msgIds", get_msgIds, set_msgIds);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RegistSelf(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			U3DEventFrame.UIBase obj = (U3DEventFrame.UIBase)ToLua.CheckObject(L, 1, typeof(U3DEventFrame.UIBase));
			U3DEventFrame.MonoBase arg0 = (U3DEventFrame.MonoBase)ToLua.CheckUnityObject(L, 2, typeof(U3DEventFrame.MonoBase));
			ushort[] arg1 = ToLua.CheckParamsNumber<ushort>(L, 3, count - 2);
			obj.RegistSelf(arg0, arg1);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UnRegistSelf(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			U3DEventFrame.UIBase obj = (U3DEventFrame.UIBase)ToLua.CheckObject(L, 1, typeof(U3DEventFrame.UIBase));
			U3DEventFrame.MonoBase arg0 = (U3DEventFrame.MonoBase)ToLua.CheckUnityObject(L, 2, typeof(U3DEventFrame.MonoBase));
			ushort[] arg1 = ToLua.CheckParamsNumber<ushort>(L, 3, count - 2);
			obj.UnRegistSelf(arg0, arg1);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SendMsg(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			U3DEventFrame.UIBase obj = (U3DEventFrame.UIBase)ToLua.CheckObject(L, 1, typeof(U3DEventFrame.UIBase));
			U3DEventFrame.MsgBase arg0 = (U3DEventFrame.MsgBase)ToLua.CheckObject(L, 2, typeof(U3DEventFrame.MsgBase));
			obj.SendMsg(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnDestroy(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			U3DEventFrame.UIBase obj = (U3DEventFrame.UIBase)ToLua.CheckObject(L, 1, typeof(U3DEventFrame.UIBase));
			obj.OnDestroy();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_msgIds(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			U3DEventFrame.UIBase obj = (U3DEventFrame.UIBase)o;
			ushort[] ret = obj.msgIds;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index msgIds on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_msgIds(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			U3DEventFrame.UIBase obj = (U3DEventFrame.UIBase)o;
			ushort[] arg0 = ToLua.CheckNumberArray<ushort>(L, 2);
			obj.msgIds = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index msgIds on a nil value" : e.Message);
		}
	}
}

